
# Script 5: The Open Source Manifesto Generator


echo "=========================================="
echo "      Welcome to the Manifesto Generator   "
echo "=========================================="
echo "Answer three questions to create your open source philosophy."
echo ""

# read -p displays a prompt to the user
read -p "1. Which open source tool is most important to you? (e.g., Python, Linux, VSCode): " Tool
read -p "2. What is the most important freedom in open source? (e.g., Modify, Share, Study): " Freedom
read -p "3. Why do we need open source software in the future? (one sentence): " Reason

# date formatting: %d %B %Y = Day Full-Month Year
Date=$(date '+%d %B %Y')
User_Name=$(whoami)
Output="manifesto_${User_Name}.txt"

# Creating the manifesto content
# > overwrites the file, >> appends to it
echo "------------------------------------------" > $Output
echo "      Open Source Manifesto - $Date       " >> $Output
echo "------------------------------------------" >> $Output
echo "I, $User_Name, believe that $Tool is essential for progress." >> $Output
echo "The freedom to $Freedom allows software to evolve beyond corporate limits." >> $Output
echo "In the future, open source matters because $Reason." >> $Output
echo "------------------------------------------" >> $Output
echo "Generated by Navjeeta's OSS Script." >> $Output

echo ""
echo "Manifesto saved to: $Output"
echo "Content of your manifesto:"
cat $Output
echo "=========================================="
